// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ack.proto

package com.github.yuanrw.im.protobuf.generate;

public final class Ack {
  private Ack() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AckMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.yuanrw.im.protobuf.generate.AckMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 2;</code>
     */
    boolean hasId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 2;</code>
     */
    long getId();

    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.DestType destType = 3;</code>
     */
    boolean hasDestType();
    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.DestType destType = 3;</code>
     */
    com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType getDestType();

    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>required string fromId = 4;</code>
     */
    boolean hasFromId();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>required string fromId = 4;</code>
     */
    java.lang.String getFromId();
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>required string fromId = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromIdBytes();

    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>required string destId = 5;</code>
     */
    boolean hasDestId();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>required string destId = 5;</code>
     */
    java.lang.String getDestId();
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>required string destId = 5;</code>
     */
    com.google.protobuf.ByteString
        getDestIdBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 6;</code>
     */
    boolean hasCreateTime();
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 6;</code>
     */
    long getCreateTime();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType msgType = 7;</code>
     */
    boolean hasMsgType();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType msgType = 7;</code>
     */
    com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType getMsgType();

    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>required int64 ackMsgId = 8;</code>
     */
    boolean hasAckMsgId();
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>required int64 ackMsgId = 8;</code>
     */
    long getAckMsgId();
  }
  /**
   * Protobuf type {@code com.github.yuanrw.im.protobuf.generate.AckMsg}
   */
  public  static final class AckMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.yuanrw.im.protobuf.generate.AckMsg)
      AckMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AckMsg.newBuilder() to construct.
    private AckMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckMsg() {
      destType_ = 0;
      fromId_ = "";
      destId_ = "";
      msgType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType value = com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                destType_ = rawValue;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              fromId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              destId_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              createTime_ = input.readInt64();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType value = com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                msgType_ = rawValue;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              ackMsgId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.yuanrw.im.protobuf.generate.Ack.internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.yuanrw.im.protobuf.generate.Ack.internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.class, com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code com.github.yuanrw.im.protobuf.generate.AckMsg.DestType}
     */
    public enum DestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SINGLE = 0;</code>
       */
      SINGLE(0),
      /**
       * <code>GROUP = 1;</code>
       */
      GROUP(1),
      ;

      /**
       * <code>SINGLE = 0;</code>
       */
      public static final int SINGLE_VALUE = 0;
      /**
       * <code>GROUP = 1;</code>
       */
      public static final int GROUP_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DestType valueOf(int value) {
        return forNumber(value);
      }

      public static DestType forNumber(int value) {
        switch (value) {
          case 0: return SINGLE;
          case 1: return GROUP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DestType>() {
              public DestType findValueByNumber(int number) {
                return DestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final DestType[] VALUES = values();

      public static DestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.github.yuanrw.im.protobuf.generate.AckMsg.DestType)
    }

    /**
     * Protobuf enum {@code com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DELIVERED = 0;</code>
       */
      DELIVERED(0),
      /**
       * <code>READ = 1;</code>
       */
      READ(1),
      ;

      /**
       * <code>DELIVERED = 0;</code>
       */
      public static final int DELIVERED_VALUE = 0;
      /**
       * <code>READ = 1;</code>
       */
      public static final int READ_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return DELIVERED;
          case 1: return READ;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType)
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int DESTTYPE_FIELD_NUMBER = 3;
    private int destType_;
    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.DestType destType = 3;</code>
     */
    public boolean hasDestType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *接收者类型。
     * </pre>
     *
     * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.DestType destType = 3;</code>
     */
    public com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType getDestType() {
      @SuppressWarnings("deprecation")
      com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType result = com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType.valueOf(destType_);
      return result == null ? com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType.SINGLE : result;
    }

    public static final int FROMID_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromId_;
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>required string fromId = 4;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>required string fromId = 4;</code>
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *发送者userId
     * </pre>
     *
     * <code>required string fromId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTID_FIELD_NUMBER = 5;
    private volatile java.lang.Object destId_;
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>required string destId = 5;</code>
     */
    public boolean hasDestId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>required string destId = 5;</code>
     */
    public java.lang.String getDestId() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *接收者userId
     * </pre>
     *
     * <code>required string destId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      java.lang.Object ref = destId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 6;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 6;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 7;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType msgType = 7;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType msgType = 7;</code>
     */
    public com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType result = com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType.valueOf(msgType_);
      return result == null ? com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType.DELIVERED : result;
    }

    public static final int ACKMSGID_FIELD_NUMBER = 8;
    private long ackMsgId_;
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>required int64 ackMsgId = 8;</code>
     */
    public boolean hasAckMsgId() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>required int64 ackMsgId = 8;</code>
     */
    public long getAckMsgId() {
      return ackMsgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAckMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, destType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, destId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(6, createTime_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(7, msgType_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeInt64(8, ackMsgId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, destType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, destId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, msgType_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, ackMsgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.yuanrw.im.protobuf.generate.Ack.AckMsg)) {
        return super.equals(obj);
      }
      com.github.yuanrw.im.protobuf.generate.Ack.AckMsg other = (com.github.yuanrw.im.protobuf.generate.Ack.AckMsg) obj;

      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasDestType() != other.hasDestType()) return false;
      if (hasDestType()) {
        if (destType_ != other.destType_) return false;
      }
      if (hasFromId() != other.hasFromId()) return false;
      if (hasFromId()) {
        if (!getFromId()
            .equals(other.getFromId())) return false;
      }
      if (hasDestId() != other.hasDestId()) return false;
      if (hasDestId()) {
        if (!getDestId()
            .equals(other.getDestId())) return false;
      }
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (getCreateTime()
            != other.getCreateTime()) return false;
      }
      if (hasMsgType() != other.hasMsgType()) return false;
      if (hasMsgType()) {
        if (msgType_ != other.msgType_) return false;
      }
      if (hasAckMsgId() != other.hasAckMsgId()) return false;
      if (hasAckMsgId()) {
        if (getAckMsgId()
            != other.getAckMsgId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasDestType()) {
        hash = (37 * hash) + DESTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + destType_;
      }
      if (hasFromId()) {
        hash = (37 * hash) + FROMID_FIELD_NUMBER;
        hash = (53 * hash) + getFromId().hashCode();
      }
      if (hasDestId()) {
        hash = (37 * hash) + DESTID_FIELD_NUMBER;
        hash = (53 * hash) + getDestId().hashCode();
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreateTime());
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
      }
      if (hasAckMsgId()) {
        hash = (37 * hash) + ACKMSGID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAckMsgId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.yuanrw.im.protobuf.generate.Ack.AckMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.yuanrw.im.protobuf.generate.AckMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.yuanrw.im.protobuf.generate.AckMsg)
        com.github.yuanrw.im.protobuf.generate.Ack.AckMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.yuanrw.im.protobuf.generate.Ack.internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.yuanrw.im.protobuf.generate.Ack.internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.class, com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.Builder.class);
      }

      // Construct using com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        destType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        fromId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        destId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        ackMsgId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.yuanrw.im.protobuf.generate.Ack.internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_descriptor;
      }

      @java.lang.Override
      public com.github.yuanrw.im.protobuf.generate.Ack.AckMsg getDefaultInstanceForType() {
        return com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.yuanrw.im.protobuf.generate.Ack.AckMsg build() {
        com.github.yuanrw.im.protobuf.generate.Ack.AckMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.yuanrw.im.protobuf.generate.Ack.AckMsg buildPartial() {
        com.github.yuanrw.im.protobuf.generate.Ack.AckMsg result = new com.github.yuanrw.im.protobuf.generate.Ack.AckMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.destType_ = destType_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.destId_ = destId_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.createTime_ = createTime_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.ackMsgId_ = ackMsgId_;
          to_bitField0_ |= 0x00000080;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.yuanrw.im.protobuf.generate.Ack.AckMsg) {
          return mergeFrom((com.github.yuanrw.im.protobuf.generate.Ack.AckMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.yuanrw.im.protobuf.generate.Ack.AckMsg other) {
        if (other == com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDestType()) {
          setDestType(other.getDestType());
        }
        if (other.hasFromId()) {
          bitField0_ |= 0x00000008;
          fromId_ = other.fromId_;
          onChanged();
        }
        if (other.hasDestId()) {
          bitField0_ |= 0x00000010;
          destId_ = other.destId_;
          onChanged();
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasAckMsgId()) {
          setAckMsgId(other.getAckMsgId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasDestType()) {
          return false;
        }
        if (!hasFromId()) {
          return false;
        }
        if (!hasDestId()) {
          return false;
        }
        if (!hasCreateTime()) {
          return false;
        }
        if (!hasMsgType()) {
          return false;
        }
        if (!hasAckMsgId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.yuanrw.im.protobuf.generate.Ack.AckMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.yuanrw.im.protobuf.generate.Ack.AckMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 2;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int destType_ = 0;
      /**
       * <pre>
       *接收者类型。
       * </pre>
       *
       * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.DestType destType = 3;</code>
       */
      public boolean hasDestType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *接收者类型。
       * </pre>
       *
       * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.DestType destType = 3;</code>
       */
      public com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType getDestType() {
        @SuppressWarnings("deprecation")
        com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType result = com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType.valueOf(destType_);
        return result == null ? com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType.SINGLE : result;
      }
      /**
       * <pre>
       *接收者类型。
       * </pre>
       *
       * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.DestType destType = 3;</code>
       */
      public Builder setDestType(com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.DestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        destType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者类型。
       * </pre>
       *
       * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.DestType destType = 3;</code>
       */
      public Builder clearDestType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        destType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fromId_ = "";
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>required string fromId = 4;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>required string fromId = 4;</code>
       */
      public java.lang.String getFromId() {
        java.lang.Object ref = fromId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>required string fromId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromIdBytes() {
        java.lang.Object ref = fromId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>required string fromId = 4;</code>
       */
      public Builder setFromId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>required string fromId = 4;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fromId_ = getDefaultInstance().getFromId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者userId
       * </pre>
       *
       * <code>required string fromId = 4;</code>
       */
      public Builder setFromIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destId_ = "";
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>required string destId = 5;</code>
       */
      public boolean hasDestId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>required string destId = 5;</code>
       */
      public java.lang.String getDestId() {
        java.lang.Object ref = destId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            destId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>required string destId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDestIdBytes() {
        java.lang.Object ref = destId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>required string destId = 5;</code>
       */
      public Builder setDestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>required string destId = 5;</code>
       */
      public Builder clearDestId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者userId
       * </pre>
       *
       * <code>required string destId = 5;</code>
       */
      public Builder setDestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        destId_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 6;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 6;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 6;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000020;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 6;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType msgType = 7;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType msgType = 7;</code>
       */
      public com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType result = com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType.valueOf(msgType_);
        return result == null ? com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType.DELIVERED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType msgType = 7;</code>
       */
      public Builder setMsgType(com.github.yuanrw.im.protobuf.generate.Ack.AckMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.github.yuanrw.im.protobuf.generate.AckMsg.MsgType msgType = 7;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private long ackMsgId_ ;
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>required int64 ackMsgId = 8;</code>
       */
      public boolean hasAckMsgId() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>required int64 ackMsgId = 8;</code>
       */
      public long getAckMsgId() {
        return ackMsgId_;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>required int64 ackMsgId = 8;</code>
       */
      public Builder setAckMsgId(long value) {
        bitField0_ |= 0x00000080;
        ackMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>required int64 ackMsgId = 8;</code>
       */
      public Builder clearAckMsgId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ackMsgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.yuanrw.im.protobuf.generate.AckMsg)
    }

    // @@protoc_insertion_point(class_scope:com.github.yuanrw.im.protobuf.generate.AckMsg)
    private static final com.github.yuanrw.im.protobuf.generate.Ack.AckMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.yuanrw.im.protobuf.generate.Ack.AckMsg();
    }

    public static com.github.yuanrw.im.protobuf.generate.Ack.AckMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AckMsg>
        PARSER = new com.google.protobuf.AbstractParser<AckMsg>() {
      @java.lang.Override
      public AckMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.yuanrw.im.protobuf.generate.Ack.AckMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tack.proto\022&com.github.yuanrw.im.protob" +
      "uf.generate\"\306\002\n\006AckMsg\022\017\n\007version\030\001 \002(\005\022" +
      "\n\n\002id\030\002 \002(\003\022I\n\010destType\030\003 \002(\01627.com.gith" +
      "ub.yuanrw.im.protobuf.generate.AckMsg.De" +
      "stType\022\016\n\006fromId\030\004 \002(\t\022\016\n\006destId\030\005 \002(\t\022\022" +
      "\n\ncreateTime\030\006 \002(\003\022G\n\007msgType\030\007 \002(\01626.co" +
      "m.github.yuanrw.im.protobuf.generate.Ack" +
      "Msg.MsgType\022\020\n\010ackMsgId\030\010 \002(\003\"!\n\010DestTyp" +
      "e\022\n\n\006SINGLE\020\000\022\t\n\005GROUP\020\001\"\"\n\007MsgType\022\r\n\tD" +
      "ELIVERED\020\000\022\010\n\004READ\020\001B\005B\003Ack"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_yuanrw_im_protobuf_generate_AckMsg_descriptor,
        new java.lang.String[] { "Version", "Id", "DestType", "FromId", "DestId", "CreateTime", "MsgType", "AckMsgId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
