// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.yrw.im.proto.generate;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InternalMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yrw.im.proto.generate.InternalMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.Module from = 2;</code>
     */
    boolean hasFrom();
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.Module from = 2;</code>
     */
    com.yrw.im.proto.generate.Internal.InternalMsg.Module getFrom();

    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.Module dest = 3;</code>
     */
    boolean hasDest();
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.Module dest = 3;</code>
     */
    com.yrw.im.proto.generate.Internal.InternalMsg.Module getDest();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 4;</code>
     */
    boolean hasCreateTime();
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 4;</code>
     */
    long getCreateTime();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.InternalMsgType msgType = 5;</code>
     */
    boolean hasMsgType();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.InternalMsgType msgType = 5;</code>
     */
    com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType getMsgType();

    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 6;</code>
     */
    boolean hasMsgBody();
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 6;</code>
     */
    java.lang.String getMsgBody();
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 6;</code>
     */
    com.google.protobuf.ByteString
        getMsgBodyBytes();
  }
  /**
   * Protobuf type {@code com.yrw.im.proto.generate.InternalMsg}
   */
  public  static final class InternalMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yrw.im.proto.generate.InternalMsg)
      InternalMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InternalMsg.newBuilder() to construct.
    private InternalMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InternalMsg() {
      from_ = 0;
      dest_ = 0;
      msgType_ = 0;
      msgBody_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.yrw.im.proto.generate.Internal.InternalMsg.Module value = com.yrw.im.proto.generate.Internal.InternalMsg.Module.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                from_ = rawValue;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.yrw.im.proto.generate.Internal.InternalMsg.Module value = com.yrw.im.proto.generate.Internal.InternalMsg.Module.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                dest_ = rawValue;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createTime_ = input.readInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType value = com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                msgType_ = rawValue;
              }
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              msgBody_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yrw.im.proto.generate.Internal.internal_static_com_yrw_im_proto_generate_InternalMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yrw.im.proto.generate.Internal.internal_static_com_yrw_im_proto_generate_InternalMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yrw.im.proto.generate.Internal.InternalMsg.class, com.yrw.im.proto.generate.Internal.InternalMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code com.yrw.im.proto.generate.InternalMsg.Module}
     */
    public enum Module
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONNECTOR = 0;</code>
       */
      CONNECTOR(0),
      /**
       * <code>TRANSFER = 1;</code>
       */
      TRANSFER(1),
      /**
       * <code>OFFLINE = 2;</code>
       */
      OFFLINE(2),
      /**
       * <code>CLIENT = 3;</code>
       */
      CLIENT(3),
      ;

      /**
       * <code>CONNECTOR = 0;</code>
       */
      public static final int CONNECTOR_VALUE = 0;
      /**
       * <code>TRANSFER = 1;</code>
       */
      public static final int TRANSFER_VALUE = 1;
      /**
       * <code>OFFLINE = 2;</code>
       */
      public static final int OFFLINE_VALUE = 2;
      /**
       * <code>CLIENT = 3;</code>
       */
      public static final int CLIENT_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Module valueOf(int value) {
        return forNumber(value);
      }

      public static Module forNumber(int value) {
        switch (value) {
          case 0: return CONNECTOR;
          case 1: return TRANSFER;
          case 2: return OFFLINE;
          case 3: return CLIENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Module> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Module>() {
              public Module findValueByNumber(int number) {
                return Module.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yrw.im.proto.generate.Internal.InternalMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Module[] VALUES = values();

      public static Module valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Module(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.yrw.im.proto.generate.InternalMsg.Module)
    }

    /**
     * Protobuf enum {@code com.yrw.im.proto.generate.InternalMsg.InternalMsgType}
     */
    public enum InternalMsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GREET = 0;</code>
       */
      GREET(0),
      /**
       * <code>USER_STATUS = 1;</code>
       */
      USER_STATUS(1),
      ;

      /**
       * <code>GREET = 0;</code>
       */
      public static final int GREET_VALUE = 0;
      /**
       * <code>USER_STATUS = 1;</code>
       */
      public static final int USER_STATUS_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InternalMsgType valueOf(int value) {
        return forNumber(value);
      }

      public static InternalMsgType forNumber(int value) {
        switch (value) {
          case 0: return GREET;
          case 1: return USER_STATUS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<InternalMsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          InternalMsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<InternalMsgType>() {
              public InternalMsgType findValueByNumber(int number) {
                return InternalMsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yrw.im.proto.generate.Internal.InternalMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final InternalMsgType[] VALUES = values();

      public static InternalMsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private InternalMsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.yrw.im.proto.generate.InternalMsg.InternalMsgType)
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private int from_;
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.Module from = 2;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.Module from = 2;</code>
     */
    public com.yrw.im.proto.generate.Internal.InternalMsg.Module getFrom() {
      @SuppressWarnings("deprecation")
      com.yrw.im.proto.generate.Internal.InternalMsg.Module result = com.yrw.im.proto.generate.Internal.InternalMsg.Module.valueOf(from_);
      return result == null ? com.yrw.im.proto.generate.Internal.InternalMsg.Module.CONNECTOR : result;
    }

    public static final int DEST_FIELD_NUMBER = 3;
    private int dest_;
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.Module dest = 3;</code>
     */
    public boolean hasDest() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.Module dest = 3;</code>
     */
    public com.yrw.im.proto.generate.Internal.InternalMsg.Module getDest() {
      @SuppressWarnings("deprecation")
      com.yrw.im.proto.generate.Internal.InternalMsg.Module result = com.yrw.im.proto.generate.Internal.InternalMsg.Module.valueOf(dest_);
      return result == null ? com.yrw.im.proto.generate.Internal.InternalMsg.Module.CONNECTOR : result;
    }

    public static final int CREATETIME_FIELD_NUMBER = 4;
    private long createTime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 4;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 4;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 5;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.InternalMsgType msgType = 5;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.yrw.im.proto.generate.InternalMsg.InternalMsgType msgType = 5;</code>
     */
    public com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType getMsgType() {
      @SuppressWarnings("deprecation")
      com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType result = com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType.valueOf(msgType_);
      return result == null ? com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType.GREET : result;
    }

    public static final int MSGBODY_FIELD_NUMBER = 6;
    private volatile java.lang.Object msgBody_;
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 6;</code>
     */
    public boolean hasMsgBody() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 6;</code>
     */
    public java.lang.String getMsgBody() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgBody_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, from_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, dest_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeEnum(5, msgType_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, msgBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, from_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, dest_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, msgType_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, msgBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yrw.im.proto.generate.Internal.InternalMsg)) {
        return super.equals(obj);
      }
      com.yrw.im.proto.generate.Internal.InternalMsg other = (com.yrw.im.proto.generate.Internal.InternalMsg) obj;

      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasFrom() != other.hasFrom()) return false;
      if (hasFrom()) {
        if (from_ != other.from_) return false;
      }
      if (hasDest() != other.hasDest()) return false;
      if (hasDest()) {
        if (dest_ != other.dest_) return false;
      }
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (getCreateTime()
            != other.getCreateTime()) return false;
      }
      if (hasMsgType() != other.hasMsgType()) return false;
      if (hasMsgType()) {
        if (msgType_ != other.msgType_) return false;
      }
      if (hasMsgBody() != other.hasMsgBody()) return false;
      if (hasMsgBody()) {
        if (!getMsgBody()
            .equals(other.getMsgBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + from_;
      }
      if (hasDest()) {
        hash = (37 * hash) + DEST_FIELD_NUMBER;
        hash = (53 * hash) + dest_;
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreateTime());
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
      }
      if (hasMsgBody()) {
        hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
        hash = (53 * hash) + getMsgBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yrw.im.proto.generate.Internal.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yrw.im.proto.generate.Internal.InternalMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yrw.im.proto.generate.InternalMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yrw.im.proto.generate.InternalMsg)
        com.yrw.im.proto.generate.Internal.InternalMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yrw.im.proto.generate.Internal.internal_static_com_yrw_im_proto_generate_InternalMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yrw.im.proto.generate.Internal.internal_static_com_yrw_im_proto_generate_InternalMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yrw.im.proto.generate.Internal.InternalMsg.class, com.yrw.im.proto.generate.Internal.InternalMsg.Builder.class);
      }

      // Construct using com.yrw.im.proto.generate.Internal.InternalMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dest_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        msgBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yrw.im.proto.generate.Internal.internal_static_com_yrw_im_proto_generate_InternalMsg_descriptor;
      }

      @java.lang.Override
      public com.yrw.im.proto.generate.Internal.InternalMsg getDefaultInstanceForType() {
        return com.yrw.im.proto.generate.Internal.InternalMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.yrw.im.proto.generate.Internal.InternalMsg build() {
        com.yrw.im.proto.generate.Internal.InternalMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yrw.im.proto.generate.Internal.InternalMsg buildPartial() {
        com.yrw.im.proto.generate.Internal.InternalMsg result = new com.yrw.im.proto.generate.Internal.InternalMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dest_ = dest_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.createTime_ = createTime_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgBody_ = msgBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yrw.im.proto.generate.Internal.InternalMsg) {
          return mergeFrom((com.yrw.im.proto.generate.Internal.InternalMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yrw.im.proto.generate.Internal.InternalMsg other) {
        if (other == com.yrw.im.proto.generate.Internal.InternalMsg.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasDest()) {
          setDest(other.getDest());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgBody()) {
          bitField0_ |= 0x00000020;
          msgBody_ = other.msgBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasFrom()) {
          return false;
        }
        if (!hasDest()) {
          return false;
        }
        if (!hasCreateTime()) {
          return false;
        }
        if (!hasMsgType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yrw.im.proto.generate.Internal.InternalMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yrw.im.proto.generate.Internal.InternalMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private int from_ = 0;
      /**
       * <pre>
       *发送模块
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.Module from = 2;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *发送模块
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.Module from = 2;</code>
       */
      public com.yrw.im.proto.generate.Internal.InternalMsg.Module getFrom() {
        @SuppressWarnings("deprecation")
        com.yrw.im.proto.generate.Internal.InternalMsg.Module result = com.yrw.im.proto.generate.Internal.InternalMsg.Module.valueOf(from_);
        return result == null ? com.yrw.im.proto.generate.Internal.InternalMsg.Module.CONNECTOR : result;
      }
      /**
       * <pre>
       *发送模块
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.Module from = 2;</code>
       */
      public Builder setFrom(com.yrw.im.proto.generate.Internal.InternalMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        from_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送模块
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.Module from = 2;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = 0;
        onChanged();
        return this;
      }

      private int dest_ = 0;
      /**
       * <pre>
       *接收模块
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.Module dest = 3;</code>
       */
      public boolean hasDest() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *接收模块
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.Module dest = 3;</code>
       */
      public com.yrw.im.proto.generate.Internal.InternalMsg.Module getDest() {
        @SuppressWarnings("deprecation")
        com.yrw.im.proto.generate.Internal.InternalMsg.Module result = com.yrw.im.proto.generate.Internal.InternalMsg.Module.valueOf(dest_);
        return result == null ? com.yrw.im.proto.generate.Internal.InternalMsg.Module.CONNECTOR : result;
      }
      /**
       * <pre>
       *接收模块
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.Module dest = 3;</code>
       */
      public Builder setDest(com.yrw.im.proto.generate.Internal.InternalMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        dest_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收模块
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.Module dest = 3;</code>
       */
      public Builder clearDest() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dest_ = 0;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 4;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 4;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 4;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000008;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 4;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.InternalMsgType msgType = 5;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.InternalMsgType msgType = 5;</code>
       */
      public com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType getMsgType() {
        @SuppressWarnings("deprecation")
        com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType result = com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType.valueOf(msgType_);
        return result == null ? com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType.GREET : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.InternalMsgType msgType = 5;</code>
       */
      public Builder setMsgType(com.yrw.im.proto.generate.Internal.InternalMsg.InternalMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.yrw.im.proto.generate.InternalMsg.InternalMsgType msgType = 5;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgBody_ = "";
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 6;</code>
       */
      public boolean hasMsgBody() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 6;</code>
       */
      public java.lang.String getMsgBody() {
        java.lang.Object ref = msgBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgBody_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBodyBytes() {
        java.lang.Object ref = msgBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 6;</code>
       */
      public Builder setMsgBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 6;</code>
       */
      public Builder clearMsgBody() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 6;</code>
       */
      public Builder setMsgBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgBody_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yrw.im.proto.generate.InternalMsg)
    }

    // @@protoc_insertion_point(class_scope:com.yrw.im.proto.generate.InternalMsg)
    private static final com.yrw.im.proto.generate.Internal.InternalMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yrw.im.proto.generate.Internal.InternalMsg();
    }

    public static com.yrw.im.proto.generate.Internal.InternalMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InternalMsg>
        PARSER = new com.google.protobuf.AbstractParser<InternalMsg>() {
      @java.lang.Override
      public InternalMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InternalMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yrw.im.proto.generate.Internal.InternalMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yrw_im_proto_generate_InternalMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yrw_im_proto_generate_InternalMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016internal.proto\022\031com.yrw.im.proto.gener" +
      "ate\"\365\002\n\013InternalMsg\022\017\n\007version\030\001 \002(\005\022;\n\004" +
      "from\030\002 \002(\0162-.com.yrw.im.proto.generate.I" +
      "nternalMsg.Module\022;\n\004dest\030\003 \002(\0162-.com.yr" +
      "w.im.proto.generate.InternalMsg.Module\022\022" +
      "\n\ncreateTime\030\004 \002(\003\022G\n\007msgType\030\005 \002(\01626.co" +
      "m.yrw.im.proto.generate.InternalMsg.Inte" +
      "rnalMsgType\022\017\n\007msgBody\030\006 \001(\t\">\n\006Module\022\r" +
      "\n\tCONNECTOR\020\000\022\014\n\010TRANSFER\020\001\022\013\n\007OFFLINE\020\002" +
      "\022\n\n\006CLIENT\020\003\"-\n\017InternalMsgType\022\t\n\005GREET" +
      "\020\000\022\017\n\013USER_STATUS\020\001B\nB\010Internal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yrw_im_proto_generate_InternalMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yrw_im_proto_generate_InternalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yrw_im_proto_generate_InternalMsg_descriptor,
        new java.lang.String[] { "Version", "From", "Dest", "CreateTime", "MsgType", "MsgBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
